dist: focal

os:
  - linux
language: cpp
cache:
  - ccache
  - pip
  - apt

jobs:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - cmake
            - libgtest-dev
      env:
        - COMPILER=g++-10
        - CXX=g++-10
        - CC=gcc-10

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-focal
          packages:
            - clang++-11
            - cmake
            - libgtest-dev
            - libstdc++-10-dev
      env:
        - COMPILER=clang++-11
        - CXX=clang++-11
        - CC=clang-11

    - stage: deploy
      script:
        - 'nvm install lts/*'
        - npx semantic-release

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --target ggmath_tests
  - tests/ggmath_tests