dist: focal

os:
  - linux
language: cpp

jobs:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - cmake
    # - before_script:
        # - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave /usr/bin/g++ g++ /usr/bin/g++-10
      env:
        - COMPILER=g++-10
        - CXX=g++-10

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
          packages:
            - clang-10
            - cmake
        # - before_script:
        # - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/clang-10 60 --slave /usr/bin/g++ g++ /usr/bin/clang++-10
      env:
        - COMPILER=clang++-10
        - CXX=clang++-10

    - stage: deploy
      compiler: gcc
      script:
        - git config --global user.name "semantic-release (via TravisCI)"
        - git config --global user.email "semantic-release@travis"
        - pip install python-semantic-release
        - echo $TRAVIS_PULL_REQUEST
        - echo $TRAVIS_BRANCH
        - semantic-release -v Warning publish
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --target ggmath_tests
  - tests/ggmath_tests